# Site settings
title: Luis Edymerchk Laverde
email: edyhack@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programming stuff and some weird thoughts.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://edymerchk.com" # the base hostname & protocol for your site
twitter_username: edymerchk
github_username:  edymerchk

# Build settings
markdown: kramdown
